
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const ADMIN_REG_SUCCESS = 'ADMIN_REG_SUCCESS';
export const STAFF_REG_SUCCESS = 'STAFF_REG_SUCCESS';
export const MANAGER_REG_SUCCESS = 'MANAGER_REG_SUCCESS';
export const CITIZEN_REG_SUCCESS = 'CITIZEN_REG_SUCCESS';


export const MANAGER_LOGIN_SUCCESS = 'MANAGER_LOGIN_SUCCESS';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const STAFF_LOGIN_SUCCESS = 'STAFF_LOGIN_SUCCESS';
export const CITIZEN_LOGIN_SUCCESS = 'CITIZEN_LOGIN_SUCCESS';

