export const GET_CITIZEN_DTLS = 'GET_CITIZEN_DTLS';
export const POST_VACCINEDATE = 'POST_VACCINEDATE';
export const GET_VACCINEDATE = 'GET_VACCINEDATE';
export const CITIZEN_ERROR = 'CITIZEN_ERROR';

