export const CREATE_PROGRAM = 'CREATE_PROGRAM';
export const GET_STATISTICS = 'GET_STATISTICS';
export const GET_VACCINE_TYPE = 'GET_VACCINE_TYPE';
export const CREATE_POST = 'CREATE_POST';
export const GET_CITIZEN_DETAILS = 'GET_CITIZEN_DETAILS';



