
export const GET_NEXT_PROGRAM = 'GET_NEXT_PROGRAM';
export const GET_PATIENT = 'GET_PATIENT';
export const UPDATE_CITIZEN = 'UPDATE_CITIZEN';
export const UPDATE_VACINATION = 'UPDATE_VACINATION';
export const CREATE_VACCINE_TYPE = 'CREATE_VACCINE_TYPE';
export const ADD_VACCINE = 'ADD_VACCINE';




